project:
  type: website
  output-dir: docs
  resources:
    - data
    - images
    - outputs

website:
  title: "DSAN Scholarship 2025"
  favicon: "images/gu-logo.png"
  back-to-top-navigation: true
  bread-crumbs: true
    # Commenting out the navbar configuration
  navbar:
      search: true
      left: 
        - href: index.qmd
          text: Home
        - href: dashboard.qmd
          text: Dashboard
        - href: analysis.qmd
          text: Analysis
        - text: Technical Details
          menu:
            - href: data_cleaning.ipynb
              text: Data Cleaning
            - href: eda.ipynb
              text: Exploratory Data Analysis
            - href: llm-usage.qmd
              text: "LLM Usage Log"
        - href: references.qmd
          text: References

  sidebar:
    search: true
    style: "docked"
    contents:
      - text: Home
        href: index.qmd
      - text: Dashboard
        href: dashboard.qmd
      - section: Technical Details
        contents:
          - href: data_cleaning.ipynb
            text: Data Cleaning
          - href: eda.ipynb
            text: Exploratory Data Analysis
          - href: llm-usage.qmd
            text: "LLM Usage Log"
      - href: references.qmd
        text: References


  # Commenting out the sidebar configuration
  # sidebar:
  #   search: true 
  #   style: "docked"
  #   contents:
  #     - text: Home
  #       href: index.qmd
  #     - text: Report
  #       href: report.qmd
  #     - section: Technical Details
  #       contents:
  #         - href: data_cleaning.ipynb
  #           text: Data Cleaning
  #         - href: eda.qmd
  #           text: Exploratory Data Analysis
  #         - href: llm-usage.qmd
  #           text: "LLM Usage Log"
  #     - href: references.qmd
  #       text: References
  #     - href: appendix.qmd
  #       text: Appendix

format:
  html:
    theme: 
      - sandstone
      - styles.scss
    page-layout: full
    toc: true
    toc-location: right
    toc-depth: 4
