project:
  type: website
  output-dir: docs
  resources:
    - data
    - images

website:
  title: "DSAN-Viz Mini Project 2025"
  favicon: "images/gu-logo.png"
  navbar: 
    search: true
    left: 
      - href: index.qmd
        text: Homepage/Dashboard
      - href: report.qmd
        text: Report
      - text: Technical Details
        menu:
          - href: data_cleaning.qmd
            text: Data Cleaning
          - href: eda.qmd
            text: Exploratory Data Analysis
          - href: llm-usage.qmd
            text: "LLM Usage Log"
      - href: references.qmd
        text: References
      - href: appendix.qmd
        text: Appendix

format:
  html:
    theme: lumen
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 4
